cars/urls.py
from django.conf.urls import url
from.import views

app_name = 'cars'

urlpatterns = [

    url(r'^$', views.main, name='main'),
    url(r'^upcomingcars/$', views.upcoming, name='coming'),
    url(r'^carmodels/$', views.details, name='det'),
    url(r'^alert_me/(?P<which_car>[\w ]+)/$', views.formfill, name='fill'),
    url(r'^alert_me/(?P<which_car>[\w ]+)/sending_mail/$', views.mail, name='mail'),
    url(r'^used-cars\sin/(?P<city>[\w]+)/$', views.used, name="use")
]

carshar/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cars/', include('cars.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from __future__ import unicode_literals
from django.db import models


class Cars(models.Model):
    pic = models.CharField(max_length=1000, default=" ")
    type = models.CharField(max_length=100)
    name = models.CharField(max_length=500)
    company = models.CharField(max_length=500)
    price = models.IntegerField(default=0)
    launch_date = models.DateField(default=0-0-0)
    about = models.TextField(default=" ")

    def __str__(self):
        return self.company + '-' + self.name


class UsedCars(models.Model):
    company = models.CharField(max_length=500)
    name = models.CharField(max_length=1000)
    price = models.IntegerField(default=0)
    year = models.IntegerField(default=0)
    driven = models.IntegerField(default=0)
    oil = models.CharField(max_length=100)
    owner_type = models.CharField(max_length=100)
    place = models.CharField(max_length=500)
    pic = models.FileField(default=None)

    def __str__(self):
        return self.company + self.name + '-' + self.place


class Owner(models.Model):
    car = models.ForeignKey(UsedCars, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    address = models.CharField(max_length=1000)
    mobile_no = models.IntegerField(default=0)

    def __str__(self):
        return self.name + '-' + self.car.company + self.car.name + '-' + self.car.place

cars/views.py
from django.core.mail import send_mail
from django.utils.timezone import datetime
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.conf import settings
from.models import Cars, UsedCars


def main(request):
    cars = Cars.objects.filter(launch_date__gt=datetime.now())
    return render(request, 'cars/main.html', {'gadi': cars})


def upcoming(request):
    c = Cars.objects.filter(launch_date__gt=datetime.now())
    return render(request, 'cars/upcoming.html', {'cars': c})


def details(request):
    if request.method == 'POST':
        x = request.POST['faaltu']
        return HttpResponse('%s' % x)

    # return render(request, 'cars/findcars.html', {'automob': gaadia})


def formfill(request, which_car):
    return render(request, 'cars/userrequest.html', {
        'name': which_car
    })


def mail(request, which_car):
    email = request.POST['send']
    name = request.POST['naaam']
    city = request.POST['city']
    subject = 'Alert Confirmation request'
    from_email = settings.EMAIL_HOST_USER
    to_email = [email]
    contact_message = "Dear %s we have received your request to get an alert for %s ,you will be alerted when launched in %s"%(
        name, which_car, city)

    send_mail(subject,
              contact_message,
              from_email,
              to_email,
              fail_silently=False)
    return render(request, 'cars/thankyou.html', {'message': 'email sent succesfully'})


def used(request, city):
    vehicle = UsedCars.objects.filter(place__startswith=city)
    return render(request, 'cars/used.html', {'vehicle': vehicle})

cars/templates/cars/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cars{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Candal' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Orbitron:400,500,700,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Inconsolata:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Courgette' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'cars/design.css' %}" />
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'cars:main' %}">CARSHAR</a>
        </div>
            <ul class="nav navbar-nav">
                <li class="dropdown"><a class="dropdown-toogle" data-toggle="dropdown" href="#">NEW <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'cars:coming' %}">Upcoming Cars</a></li>
                        <li><a href="#">Dealers&Service centers</a></li>
                    </ul>
                </li>
                <li class="dropdown"><a id="dLabel" role="button" data-toggle="dropdown">
                USED CARS <span class="caret"></span></a>
                    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                        <li class="dropdown-submenu"><a href="#">Used Cars In your City</a>
                            <ul class="dropdown-menu" >
                                <li><a href="{% url 'cars:use' 'Ghaziabad' %}">Ghaziabad</a></li>
                                <li><a href="{% url 'cars:use' 'Delhi' %}">Delhi</a></li>
                                <li><a href="{% url 'cars:use' 'Gurugram' %}">Gurugram</a></li>
                                <li><a href="{% url 'cars:use' 'Noida' %}">Noida</a></li>
                                <li><a href="{% url 'cars:use' 'Chandigarh' %}">Chandigarh</a></li>
                                <li><a href="{% url 'cars:use' 'Bangalore' %}">Bangalore</a></li>
                                <li><a href="{% url 'cars:use' 'Chennai' %}">Chennai</a></li>
                                <li><a href="{% url 'cars:use' 'Hyderabad' %}">Hyderabad</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown"><a  class="dropdown-toggle" data-toggle="dropdown" href="#">NEWS & REVIEWS<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Car News</a> </li>
                        <li><a href="#">User Reviews</a></li>
                    </ul>
                </li>

            </ul>
            <form class="navbar-form navbar-right" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

cars/templates/cars/findcars.html
{% extends 'cars/base.html' %}
{% block body %}
    {% load staticfiles %}

    {% for car in automob %}
        <div class="carpic">
            <img src="{% static 'cars/images/'|add:car.name|add:'.jpg'%}">
            <div class="det">
                <h2>{{ car.company }} {{ car.name }}</h2>
                <h4>{{ car.price }}</h4>
            </div>
        </div>
    {% endfor %}
{% endblock %}

cars/templates/cars/main.html
{% extends 'cars/base.html' %}
{% block body %}
    {% load staticfiles %}
    <script
    src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
    </script>
    <script>
        $(document).ready(function() {
            $("input").click(function (e) {
                document.getElementById('id1').value = e.target.value;
            });
        });
    </script>
    <div class="backimg">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLWZLIB6sX0KrZrl27_gTiubVKtFhet-6kOq__MeGi75M520PZVQ">
        <form action="{% url 'cars:det' %}" method="post">
            {% csrf_token %}
            <h2>Search The Right Car</h2>
            <input type="button"  value="NewCar">
            <input type="button"  value="UsedCar">
            <select name="cars">
                <option  value="Volkswagon">Volkswagon</option>
                <option  value="Tata">Tata</option>
                <option  value="Fiat">Fiat</option>
                <option  value="Audi">Audi</option>
                <option  value="Maruti">Maruti</option>
                <option  value="Cheverlot">Chevorlet</option>
                <option  value="Toyota">Toyota</option>
                <option  value="Mistubishi">Mistubishi</option>
            </select>
            <input type="text" id="id1" name="faaltu" value="" class="abc">
            <button type="submit" value="Search" id="final" class="btn btn-primary" style="color:white;">Search</button>
        </form>
     </div>
     <div class="box1">
        <div class="one">
            <h2>For Your Quick Look</h2>
        </div>
        <div class="two">
            <a class="focus" href="{% url  'cars:coming' %}"><h3>UPCOMING</h3></a>
        </div>
        <div class="three">
            <a href=""><h3>POPULAR</h3></a>
        </div>
        <div class="box2">
            {% for car in gadi %}
                {% if forloop.counter < 5 %}
                    <div class="car{{ forloop.counter }}">
                        <img src="{% static 'cars/images/'|add:car.name|add:'.jpg'%}">
                        <h4>{{ car.company }} {{ car.name }}</h4>
                        <h4><i class="fa fa-inr" style="font-size:24px"></i> {{ car.price }}</h4>
                        <h5>{{ car.launch_date }}</h5>
                        <button type="button" class="btn btn-default" role="button" style="color: white;"><a href="{% url 'cars:fill' car.name %}">ALERT ME WHEN LAUNCHED</a></button>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="morecoming">
                <a href="{% url 'cars:coming' %}" class="btn btn-info" role="button">VIEW MORE UPCOMING CARS</a>
        </div>
    </div>
    <div class="videosbox">
        <div class="vidstext">
            <h1>Don't miss these videos</h1>
        </div>
        <div id = "myCarousel" class = "carousel slide">

   <!-- Carousel indicators -->
           <ol class = "carousel-indicators">
              <li data-target = "#myCarousel" data-slide-to = "0" class = "active"></li>
              <li data-target = "#myCarousel" data-slide-to = "1"></li>
              <li data-target = "#myCarousel" data-slide-to = "2"></li>
           </ol>

           <!-- Carousel items -->
           <div class = "carousel-inner">
              <div class = "item active">
                 <iframe width="30%" height="260px" src="https://www.youtube.com/embed/IJBiYXVJ0Q8" frameborder="0" allowfullscreen></iframe>
                 <iframe width="30%" height="260px"src="https://www.youtube.com/embed/JP8ZThlUSUs" frameborder="0" allowfullscreen></iframe>
                 <iframe width="30%" height="260px" src="https://www.youtube.com/embed/-ifwiYyofJc" frameborder="0" allowfullscreen></iframe>
              </div>

              <div class = "item">
                 <iframe  width="30%" height="260px" src="https://www.youtube.com/embed/JW6YulkMAxQ" frameborder="0" allowfullscreen></iframe>
                  <iframe width="30%" height="260px" src="https://www.youtube.com/embed/ajccHteVp7w" frameborder="0" allowfullscreen></iframe>
                  <iframe width="30%" height="260px" src="https://www.youtube.com/embed/VHaZx1CymTs" frameborder="0" allowfullscreen></iframe>
              </div>

              <div class = "item">
                 <iframe width="30%" height="260px" src="https://www.youtube.com/embed/6dOm-LTEFtU" frameborder="0" allowfullscreen></iframe>
                  <iframe width="30%" height="260px" src="https://www.youtube.com/embed/U42pFiDiAgM" frameborder="0" allowfullscreen></iframe>
                  <iframe width="30%" height="260px" src="https://www.youtube.com/embed/GASmvTPmIt4" frameborder="0" allowfullscreen></iframe>
              </div>
           </div>

           <!-- Carousel nav -->
           <a class = "carousel-control left" href = "#myCarousel" data-slide = "prev">&lsaquo;</a>
           <a class = "carousel-control right" href = "#myCarousel" data-slide = "next">&rsaquo;</a>

        </div>
    </div>
    <footer>
        <i class="fa fa-copyright">Copyright 2008-2016 Powered By Sanyam Software Pvt. Ltd. All Rights Reserved.</i>
        <i class="fa fa-facebook" aria-hidden="true"></i>
        <i class="fa fa-twitter"></i>
        <i class="fa fa-linkedin" aria-hidden="true"></i>
    </footer>
{% endblock %}

cars/templates/cars/thankyou.html
{{ message }}

cars/templates/cars/upcoming.html
{% extends 'cars/base.html' %}
{% block title %}Upcomingcars{% endblock %}
{% block body %}
    {% load staticfiles %}
    <div class="coming">
        <h3>Upcoming Cars In India</h3>
    </div>
    <div class="container">
        <div class="coming_box">
            {% for car in cars %}
                 <div class="row">
                      <div class="col-sm-4"><img src="{% static 'cars/images/'|add:car.name|add:'.jpg'%}"></div>
                      <div class="col-sm-8">
                          <div class="gadiname">
                              <h2>{{ car.company }} {{ car.name }}</h2>
                          </div>
                          <div class="launch">
                              <h4>Expected Launch Date: {{ car.launch_date }}</h4>
                          </div>
                          <div class="price">
                              <h2>Expected Price:<i class="fa fa-inr" style="font-size:24px"></i> {{ car.price }}</h2>
                          </div>
                          <div class="text">
                              <p>{{ car.about }}</p>
                          </div>
                      </div>
                 </div>
                <div class="line">
                    <h3>_____________________________________________________________________________________-</h3>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

cars/templates/cars/used.html
{% extends 'cars/base.html' %}
{% block title %}Used Cars{% endblock %}
{% block body %}
    {% for var in vehicle %}
        <div class="used">
            <div class="usedimg">
                <img src="{{ var.pic.url }}"  data-toggle="modal" data-target="#myModal{{ forloop.counter }}" id="usedpic">
                 <div id="myModal{{ forloop.counter }}" class="modal fade" role="dialog">
                    <div class="modal-dialog">
            <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">{{ var.company }} {{ var.name }} {{ var.year }}</h4>
                          </div>
                          <div class="modal-body">

                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                    </div>
                 </div>
                 <div class="info">
                    <div class="usedname">
                        <h4>{{ var.company }} {{ var.name }}</h4>&nbsp;&nbsp;
                    </div>
                    <div class="loc">
                    <span class="glyphicon glyphicon-map-marker">{{ var.place }}</span>
                    </div>
                    <div class="usedprice">
                        <h3><i class="fa fa-inr" style="font-size:24px"></i> {{ var.price }}</h3>
                    </div>
                    <div class="usedinfo">
                        <h4>{{ var.year }} <strong>.</strong> {{ var.driven }}Kms <strong>.</strong> {{ var.oil }} <strong>.</strong> {{ var.owner_type }}</h4>
                    </div>
                    <button type="button" class="btn btn-default" role="button" id="sellerbutton"><a href="#" style="text-decoration: none; color: white">GET SELLER DETAILS</a></button>
                 </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

cars/templates/cars/userrequest.html
{% extends 'cars/base.html' %}
{% block title %}Alert User{% endblock %}
{% block  body %}
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal"><img src="http://previews.123rf.com/images/valentint/valentint1506/valentint150602609/41149016-Alert-icon-Internet-button-on-white-background-Stock-Photo.jpg" style="width: 65px; height: 55px;">  Alert Me!</button>
  <img src="http://timesofindia.indiatimes.com/thumb/msid-50731900,width-400,resizemode-4/50731900.jpg" style="width: 100%;">
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Alert Me When Launched for <strong>{{ name }}</strong></h4>
      </div>
      <div class="modal-body">
       <form action="{% url 'cars:mail' name %}"  class="form-horizontal" role="form" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label  class="col-sm-2 control-label"
                              for="inputEmail3">EMAIL</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control"
                        id="inputEmail3" name="send" placeholder="Email"/>
                    </div>
                  </div>
                   <div class="form-group">
                    <label class="col-sm-2 control-label"
                          for="inputname" >NAME</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control"
                            id="inputname" name="naaam" placeholder="Full Name"/>
                    </div>
                   </div>
                   <div class="form-group">
                        <label  class="col-sm-2 control-label"
                              for="cityselect">City</label>
                            <select name="city">
                                <option  value="Ghaziabad">Ghaziabad</option>
                                <option  value="Delhi">Delhi</option>
                                <option  value="Gurugram">Gurugram</option>
                                <option  value="Noida">Noida</option>
                                <option  value="Chandigarh">Chandigarh</option>
                                <option  value="Bangalore">Bangalore</option>
                                <option  value="Chennai">Chennai</option>
                                <option  value="Hyderabad">Hyderabad</option>
                            </select>
                   </div>
                   <button type="submit" class="btn btn-default">Submit</button>
       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

{% endblock %}